### PR TITLE
process hexadecimal strings containing line breaks, but strip line breaks first (fix #273)

### LINKED ISSUE #273: Problem in part of the translation
Hello!
First of all thanks for making this amazing tool available!
Let's get to the problem .... I'm creating a small application using PDFParser.
But it cannot convert part of a pdf.

Can you help me?

I'm reading the following url:
https://dje.tjsp.jus.br/cdje/consultaSimples.do?cdVolume=14&nuDiario=2986&cdCaderno=12&nuSeqpagina=2993

And in the first occurrence of "REQDO" it should bring forward "Guaraná e Ramos Empreendimentos Imobiliários Ltda.", However bring the following set of characters "<001d0003002a00580044005500440051006900030048000300000000000000000000000000000000000000000000000000000000000000003000000000000000000030000000
440011 ["

Using the demo guys (https://www.pdfparser.org/demo) it also presents the same error.

Can you help me? Please!!!

### PR DESCRIPTION
**Pull request by Connum**
_This is the same as #344, with the mess cleaned up._

Strings decoded as hexadecimal may contain line break characters in the hexadecimal representation of the raw data. These were ignored and the hexadecimal representation was returned unprocessed, resulting in what can be seen in #273: hexadecimal strings in the otherwise decoded text content.

This fix takes line breaks in hexadecimal representation into account, stripping those line breaks before decoding.

_Please note that the CI check will expectedly fail for test case `testGetDataTmIssue336` while PR #343 is pending._

**Edit by @k00ni:** fixes #273

### CODE REVIEW

**Comment by k00ni** [comment]
Same here, unfortunately. Can't open the diff view for FontTest, because Github thinks its a binary file.

**Comment by Connum** [comment]
> 
> 
> Same here, unfortunately. Can't open the diff view for FontTest, because Github thinks its a binary file.

Yeah, right, that was an error in reasoning on my side, to think that we would now be able to see a comparison. Of course the initial state of the file is still regarded as a binary file and therefore won't be regarded for diffing. But in the future, once this is pushed, the file will be treated as a text file again.
You could copy the content of the raw file https://raw.githubusercontent.com/smalot/pdfparser/6daa665c2d98726a2dedbadc500e16380e8ebd59/tests/Integration/FontTest.php and use the diff tool of your choice to compare it to the master version locally.

Here's the diff for the change (notice the `?` before the hex code):
```diff
235c235  
<         $hexa = '<?xml version="1.0"?><body xmlns="http://www.w3.org/1999/xhtml" xmlns:xfa="http://www.xfa.org/schema/xfa-data/1.0/" xfa:APIVersion="Acrobat:19.10.0" xfa:spec="2.0.2"  style="font-size:12.0pt;text-align:left;color:?0000;font-weight:normal;font-style:norm\  
---  
>         $hexa = '<?xml version="1.0"?><body xmlns="http://www.w3.org/1999/xhtml" xmlns:xfa="http://www.xfa.org/schema/xfa-data/1.0/" xfa:APIVersion="Acrobat:19.10.0" xfa:spec="2.0.2"  style="font-size:12.0pt;text-align:left;color:0000;font-weight:normal;font-style:norm\  
```

And a Text Compare Report created with Beyond Compare (GitHub doesn't allow the upload of the html unfortunately):
grafik

I also noticed that the hex color code following the byte char was incomplete, it should be `000000`, I fixed that in an additonal commit. My guess is that it was correct at some point and somehow the first to zeroes turned into the `00` byte symbol.

**Comment by k00ni** [comment]
Using the commit itself also reveals your changes (https://github.com/smalot/pdfparser/pull/346/commits/75e23db0d283198874afc12b44184e884eb030b4). Thank you for clearing this, will look into it later on.

**Comment by k00ni** [comment]
I just saw that in your PR #345 the same line in Parser.php was changed:

https://github.com/smalot/pdfparser/pull/345/files#diff-6dd9476cf5bca6913f04bf742aacdce9

Does it mean that this PR was replaced?

**Comment by Connum** [comment]
Oh dear, I might have pushed something to the wrong branch... let me check!

**Comment by Connum** [comment]
> 
> 
> Oh dear, I might have pushed something to the wrong branch... let me check!

Yup, that was exactly what I did... Sorry for the mess in a PR that was supposed to clean up the mess! ;-)

Corrected, master merged and code linted.

**Review by k00ni — APPROVED** [review]
Looks good. Will keep this open for a few days to allow others to comment.

**Pull request merged**
