### PR TITLE
Properly decode ANSI encodings

### PR DESCRIPTION
**Pull request by davispuh**
This PR fixes several bugs which prevented from correctly decoding ANSI encodings.
For example with this PR now can correctly get text of  PDF file which doesn't have `ToUnicode` but has `WinAnsiEncoding` with differences for Windows-1257 code page

Most likely these issues are fixed: #42 #44 #88 #151 #152 #202 #241

### CODE REVIEW

**Comment by fbett** [comment]
Thx for this PR.

This also fixes a PHP 7.4 error:
````
chr() expects parameter 1 to be int, string given at smalot/pdfparser/src/Smalot/PdfParser/Font.php:494
````

**Comment by smalot** [comment]
That's a great work but some unit tests should be really appreciated

**Comment by smalot** [comment]
I just run "unit test" on your PR and some are broken.

Can you try on your side ?
```
./vendor/bin/atoum -d src/Smalot/PdfParser/Tests/ -ncc
```

**Comment by davispuh** [comment]
I actually didn't even check them so most likely they need fixing.

**Comment by k00ni** [comment]
Hey @davispuh, there are a few things before we can merge this:

* [ ] merge in current `master` branch
* [ ] run `php vendor/bin/php-cs-fixer fix` in the terminal (applies our new coding styles)
* [ ] fix failing tests

I hope we can finish this, this code seems important to other issues/PR's too.

**Comment by davispuh** [comment]
I'm not using this library anymore and I don't really have time to complete this so you can just make new PR and fix whatever needs to be fixed.
That test fails because `$currentFont` seems to be `null` but I don't really see how that could happen.

**Comment by k00ni** [comment]
Closed due to no progress. I checked some of the issues mentioned here, there was no indication that this PR helped them.

**Comment by davispuh** [comment]
> there was no indication that this PR helped them.

That's weird, I didn't saw anyone actually testing this. It did fix a lot of issues for me. Anyway I guess not my problem anymore.

**Pull request closed without merging**
