### PR TITLE
Rework documentation

### PR DESCRIPTION
**Pull request by rubenvanerk**
Here's my shot at a new README. We might be able to get away with putting the documentation in here, but I'm not too sure.

Related: #498

### CODE REVIEW

**Comment by k00ni** [comment]
Thank you!

I took the liberty and made some changes in your branch. Hope its OK. English is not my mother tongue so you might find instances to improve.

**Comment by k00ni** [comment]
_I refined some things and added latest wiki-content made by @Reqrefusion._

What is left to do here?

@Reqrefusion After this got accepted and merged I would like to remove all content from wiki and only leave a hint to our new documentation. That way there is no confusion where to find latest documentation. What do you think? 

If there is anything I missed, please give me a hint.

**Comment by k00ni** [comment]
OK, I will leave this open until end of this week. If there are no objections or comments, this PR gets merged afterwards. Documentation is way from finished but with this work there is a good basement in my opinion.

**Review by k00ni — APPROVED** [review]

**Comment by Reqrefusion** [comment]
I feel bad seeing this so late. It seems like the end of Wiki has come. One of Github's nice but insufficient features. I will still make a few changes to the config. The current config is not very descriptive. The table I created beforehand makes trial and error easier.

**Pull request merged**
