### PR TITLE
rely on getTextArray() in getDataTm() to extract the texts

### PR DESCRIPTION
**Pull request by Connum**
Instead of parsing the text content manually, falling prone to overseeing things like hexadecimal text encoding etc., I changed the code to rely on the result of `getTextArray()`.

I also added a test case assertion for the exemplary dummy file from #336. The tests for the other files still pass, so there seem to be no side-effects.

Looking forward to others' input, especially from original author @izabala

### CODE REVIEW

**Comment by izabala** [comment]
Ok.. I was working on solving this... but if this is a better way to do it... it is welcome.

**Comment by izabala** [comment]
It really seems to be a better solution!!!!  Thanks!

**Comment by k00ni** [comment]
Is it ready to be merged?

**Comment by Connum** [comment]
All the tests pass and I didn't encounter any issues so far, so I have no
objection!

**Comment by k00ni** [comment]
OK, will keep it open for a week to allow others to comment.

**Comment by k00ni** [comment]
I moved your test code to a separate test.

**Comment by k00ni** [comment]
Thank you everyone.

**Comment by k00ni** [comment]
[PageTest::testGetDataTmIssue336](testGetDataTmIssue336) currently fails on master.

Ref:
* #336
* https://travis-ci.org/github/smalot/pdfparser/builds/730197751

**Pull request merged**
