### PR TITLE
fix Call to a member function getFontSpaceLimit() on null

### PR DESCRIPTION
**Pull request by xfolder**

### CODE REVIEW

**Comment by k00ni** [comment]
Thank you for your pull request. Please provide an example code or PDF which triggers the error.

ref: #375

**Comment by parijke** [comment]
This does not fix the error for me

**Comment by k00ni** [comment]
@parijke can you provide us an example PDF (free of charge and without obligations) or input (like example string), which triggers the error? 

@xfolder I wont accept a pull request without proof that it fixes something.

**Comment by xfolder** [comment]
`$file = "example.pdf";
$parser = new Parser();
$pdf    = $parser->parseFile($file);
$pages = $pdf->getPages();

foreach ($pages as $index => $page)
{
    $text = $page->getTextXY(181.56, 816.95, 5); //<- throw Call to a member function getFontSpaceLimit() on null
}
`
I can't attach the pdf file because it contains sensitive informations.

**Comment by suuuunto** [comment]
[ts_vonti_604496eba7101.pdf](https://github.com/smalot/pdfparser/files/6259902/ts_vonti_604496eba7101.pdf)

example file where i get the error

**Comment by k00ni** [comment]
Thank you @suuuunto, but your PDF doesn't trigger the error for me. Instead I see the following error:

> Error: Call to undefined method Smalot\PdfParser\Element\ElementMissing::getSectionsText()
/home/runner/work/pdfparser/pdfparser/src/Smalot/PdfParser/Page.php:309
/home/runner/work/pdfparser/pdfparser/src/Smalot/PdfParser/Page.php:334
/home/runner/work/pdfparser/pdfparser/src/Smalot/PdfParser/Page.php:411
/home/runner/work/pdfparser/pdfparser/src/Smalot/PdfParser/Page.php:557
/home/runner/work/pdfparser/pdfparser/src/Smalot/PdfParser/Page.php:755
/home/runner/work/pdfparser/pdfparser/tests/Integration/PDFObjectTest.php:246

([See failing test.](https://github.com/smalot/pdfparser/runs/2276101472?check_suite_focus=true#step:6:57))

I am also not sure if we can use the PDF, because it may contain copyright protected texts. Do you have the approval of Bank Vontobel AG, Zurich?

@xfolder you proposed the pull request using `master` branch in your fork. I can't say if you use it elsewhere so I avoided to push my changes. Instead I created a "proxy" branch: [`fix/replace-pr-403-getFontSpaceLimit`](https://github.com/smalot/pdfparser/tree/fix/replace-pr-403-getFontSpaceLimit). This PR will be closed and replaced by it most likely.

**TODO list:**
* [ ] remove change in Github workflow

**Comment by k00ni** [comment]
This PR is superseded by #406.

**Comment by suuuunto** [comment]
I am quite sure, I was getting the Space Limit error. Could it be a versioning thing, because I dont use the composer... where I can find out which version I use? I implement the libary via /lib/pdfparser-master/**alt_autoload.php-dist**

Regarding the copyright, I don't think it is a problem. I can not find a critical statement in it.

**Comment by parijke** [comment]
https://pdfparser.org/demo throws the error using this file

**Comment by k00ni** [comment]
@suuuunto Please download latest code from https://github.com/smalot/pdfparser/archive/refs/heads/master.zip and try again.

> Regarding the copyright, I don't think it is a problem. I can not find a critical statement in it.

In Germany texts like these are copyright protected by default because they are creative work (to some extent), as far as I know. I may be wrong here, but I am hesitant when seeing PDFs from Companies and such.

> https://pdfparser.org/demo throws the error using this file

I can't check which version runs on pdfparser.org. CC @smalot

**Comment by StudPro** [comment]
Hi @k00ni ,
I tried last version with php 7.3 and 7.4 but with same error. I attached a file, you try it. 
[Martucci et al.pdf](https://github.com/smalot/pdfparser/files/6492106/Martucci.et.al.pdf)

**Pull request closed without merging**
