### PR TITLE
Fix infite loop when xref table corrupted

### PR DESCRIPTION
**Pull request by partulaj**
Hello,

I open a PR with the modification suggested for issue #372 if you can take a look

Thank you

### CODE REVIEW

**Comment by k00ni** [comment]
@partulaj thank you for your contribution!

Can you provide a few tests please, which show problems you solved with your fix?

**Comment by partulaj** [comment]
Unfortunately I can't provide the file on which we had the issue since it contain some confidential informations, but I will try to take a closer look to see if I can manage to find a way to make this testable

**Comment by k00ni** [comment]
If we can figure out a minimal example which causes the infinite loop, I can help you with tests (see my last comment on #372).

**Comment by k00ni** [comment]
Simple test added, thanks for your help @partulaj. Good to go.

**Comment by aurelianzaha** [comment]
@k00ni are you planning to do a new release after this fix?

**Comment by k00ni** [comment]
I didn't plan a new release, but I can make a new one soon, no problem.

**Comment by aurelianzaha** [comment]
> I didn't plan a new release, but I can make a new one soon, no problem.

That would be appreciated, so I can properly include the new version in the composer file.

**Comment by k00ni** [comment]
New release published: https://github.com/smalot/pdfparser/releases/tag/v0.18.1

**Pull request merged**
