### PR TITLE
Fix array access on integer for php7.4

### LINKED ISSUE #267: In Parser.php line 154: Notice: Trying to access array offset on value of type int
Hi
I have an error :
`In Parser.php line 154: Notice: Trying to access array offset on value of type int 
`

### PR DESCRIPTION
**Pull request by PaulBehrendtVentoro**
fixes "Notice: Trying to access array offset on value of type int" for certain PDFs

### CODE REVIEW

**Comment by k00ni** [comment]
Looks good to me. Thank you @PaulBehrendtVentoro!

*I let this open for a day or two in case someone wants to comment.*

**Comment by PaulBehrendtVentoro** [comment]
btw. this does not fix the "Missing Catalog" thing as your test indicates.
So it shouldn't close #267 .

**Comment by k00ni** [comment]
> btw. this does not fix the "Missing Catalog" thing as your test indicates. So it shouldn't close #267.

You are right. But Github thinks that and will close issue #267 on merge. Maybe its because in your initial post you wrote "fixes #267"?

**Comment by PaulBehrendtVentoro** [comment]
yeah i didnt know that. looks alright now

**Comment by k00ni** [comment]
**Notice to myself:** after merging, remove branch `issue/267`.

**Pull request merged**
