### PR TITLE
Adding more dedicated exceptions

### PR DESCRIPTION
**Pull request by ThomasLandauer**
# Type of pull request

* [ ] Bug fix (involves code and configuration changes)
* [ ] New feature (involves code and configuration changes)
* [ ] Documentation update
* [x] Something else

# About

Adding 2 dedicated exceptions, following the path of https://github.com/smalot/pdfparser/pull/433

2 remarks:
* Please create a file `CONTRIBUTING.md`, according to https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors and include all information from the checklist (here below)
* I don't know how to run the unit tests, nor cs-fixer.

# Checklist for code / configuration changes

*In case you changed the code/configuration, please read each of the following checkboxes as they contain valuable information:*

* [ ] Please add at least **one test case** (unit test, system test, ...) to demonstrate that the change is working. If existing code was changed, your tests cover these code parts as well.
     By the way, you don't have to provide a full fledged PDF file to demonstrate a fix. Instead a unit test may be sufficient sometimes,
     please have a look at [FontTest](https://github.com/smalot/pdfparser/blob/master/tests/PHPUnit/Unit/FontTest.php#L40) for example code.
     Code changes without any tests are likely to be rejected. If you dont know how to write tests, no problem, tell us upfront and we may add them ourselves or discuss other ways.
* [ ] Please run **PHP-CS-Fixer** before committing, to confirm with our coding styles. See https://github.com/smalot/pdfparser/blob/master/.php-cs-fixer.php for more information about our coding styles.
* [ ] In case you **fix an existing issue**, please do one of the following:
  * [ ] Write in this text something like `fixes #1234` to outline that you are providing a fix for the issue `#1234`.
  * [ ] After the pull request was created, you will find on the right side a section called **Development**. There issues can be selected which will be closed after the your pull request got merged.
* [ ] In case you changed internal behavior or functionality, please check our documentation to make sure these changes are **documented properly**: https://github.com/smalot/pdfparser/tree/master/doc
* [ ] In case you want to discuss new ideas/changes and you are not sure, just create a pull request and mark it as **a draft**
      (see [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests) for more information).
      This will tell us, that it is not ready for merge, but you want to discuss certain issues.

### CODE REVIEW

**Comment by k00ni** [comment]
:+1: I like your idea of dedicated exceptions. While we are at it, can you think other exception types?

_The remarks are also important, but I would like to discuss these in a separate issue/pull request. A dedicated CONTRIBUTING.md file seems to be a good idea. Would you mind suggesting one in a separate PR?_

**Comment by ThomasLandauer** [comment]
> While we are at it, can you think of other exception types?

Fulltext search for `\Exception` yields some hits. Do you want me to go through them and create exceptions? (But I'd just take the current exception message and create a class from it - I won't research the context) Or just leave it up to others who have a real need (and know why/when it occurs)?

> A dedicated CONTRIBUTING.md file seems to be a good idea. Would you mind suggesting one in a separate PR?_

I'm a beginner with git, so I'm probably the wrong person. As a starting point, you can copy over what you currently have. I was annoyed yesterday to find your checklist only *after* I had finished my PR - so the idea is just to tell people *upfront* :-)

**Comment by k00ni** [comment]
Sorry for my delayed response. To move this forward, the code should be inspected to find further instances of these exceptions. Only replacing a few instances without covering the whole code base might lead to false implications by developers when using the API.

@ThomasLandauer would you mind searching for further instances where using these new exceptions is a good idea?

**Comment by k00ni** [comment]
Closing this for now due to inactivity by the author. Feel free to comment when you want to continue working on it.

**Comment by ThomasLandauer** [comment]
Sorry, I didn't know what to do exactly. Do you want me to just replace all occurrences of "my" 2 exceptions? Or create a new exception for every other `\Exception` in the code base too?

**Comment by k00ni** [comment]
As I said before, to move this forward the code should be inspected to find further instances of these exceptions. Only replacing a few instances without covering the whole code base might lead to false implications by developers when using the API.

**Review by k00ni — APPROVED** [review]
Thanks for checking.

**Here is a brief summary of my latest changes:**
- added a short comment for each new exception
- added another exception ([NotImplementedException](https://github.com/smalot/pdfparser/pull/739/files#diff-a66fa4f5d42e4303e8c348182445e6d8fa52275b422531118043414f5a435483))
- fixed coding style issues (`ran dev-tools/vendor/bin/php-cs-fixer fix` locally)

**Pull request merged**
